### PR TITLE
Improve information provided by First Room, some refinements to /help

### PR DESCRIPTION
**Pull request by ebullient**
Fixes gameontext/gameon#72
Fixes gameontext/gameon#73
Fixes gameontext/gameon#76
Fixes gameontext/gameon#77

Signed-off-by: Erin Schnabel schnabel@us.ibm.com

---

This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-mediator/67)

### CODE REVIEW

**Comment by BarDweller** [comment]
Review status: 0 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

_[mediator-app/src/main/java/org/gameontext/mediator/Constants.java, line 79 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURSoiK0oWGCPqN-cI4:-KURSoiK0oWGCPqN-cI5:b-bh138a) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-app/src/main/java/org/gameontext/mediator/Constants.java#L79)):_

> ``` Java
>     JsonObject COMMON_COMMANDS = Json.createObjectBuilder()
>             .add("/exits", "List room exits")
>             .add("/examine", "Examine an item. Implementaitons will vary: this may be similar to look, or may not work at all")
> ```

typo. implementations

---

_[mediator-app/src/main/java/org/gameontext/mediator/Constants.java, line 81 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURShpwrxTodB5V0Noy:-KURShpxP8gE6a-1aOuC:beh9s0w) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-app/src/main/java/org/gameontext/mediator/Constants.java#L81)):_

> ``` Java
>             .add("/examine", "Examine an item. Implementaitons will vary: this may be similar to look, or may not work at all")
>             .add("/go", "Exit the room using the specified door, e.g. `/go N`")
>             .add("/look", "Describe a room or an item. Implementaitons will vary")
> ```

typo.. implementations

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by BarDweller** [comment]
Reviewed 13 of 14 files at r1.
Review status: 10 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[mediator-wlpcfg/startup.sh, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURToY3uy1WXQUbiObS:-KURToY3uy1WXQUbiObT:btuzqbc) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-wlpcfg/startup.sh#L50)):_

> ``` Shell
> 
>   GAMEON_MODE=$(etcdctl get /global/mode)
>   export GAMEON_MODE=${GAMEON_MODE:-production}
> ```

does something need this set now? I can see this forces the value to production if it didnt get a value from etcd, wasnt aware of anything checking for 'production' state tho.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by ebullient** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[mediator-wlpcfg/startup.sh, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURToY3uy1WXQUbiObS:-KURUp6i6Jxyc0KbEWQQ:b-sot1jw) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-wlpcfg/startup.sh#L50)):_
<details><summary>

<i>Previously, BarDweller (Ozzy Osborne) wrote…</i></summary>



> does something need this set now? I can see this forces the value to production if it didnt get a value from etcd, wasnt aware of anything checking for 'production' state tho.
> </details>
> Related to the changes in server.xml to use the env var to pick up overrides (and skip the copies): 
>  <include location="${env.GAMEON_MODE}-local.xml" optional="true" />
>   <include location="${env.GAMEON_MODE}-logCollector.xml" optional="true" />
>   <include location="${env.GAMEON_MODE}-messageHub.xml" optional="true" />

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by ebullient** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[mediator-wlpcfg/startup.sh, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURToY3uy1WXQUbiObS:-KURV2XFfLyxFmcdRpYU:b-p1eqi6) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-wlpcfg/startup.sh#L50)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> Related to the changes in server.xml to use the env var to pick up overrides (and skip the copies): 
>  <include location="${env.GAMEON_MODE}-local.xml" optional="true" />
>   <include location="${env.GAMEON_MODE}-logCollector.xml" optional="true" />
>   <include location="${env.GAMEON_MODE}-messageHub.xml" optional="true" />
> </details>
>   &lt;include location="${env.GAMEON_MODE}-local.xml" optional="true" />
>   &lt;include location="${env.GAMEON_MODE}-logCollector.xml" optional="true" />
>   &lt;include location="${env.GAMEON_MODE}-messageHub.xml" optional="true" />

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by ebullient** [comment]
Review status: 9 of 11 files reviewed at latest revision, 3 unresolved discussions.

---

_[mediator-app/src/main/java/org/gameontext/mediator/Constants.java, line 79 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURSoiK0oWGCPqN-cI4:-KURV9hNYZYwvcCFvL07:b-896fix) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-app/src/main/java/org/gameontext/mediator/Constants.java#L79)):_
<details><summary>

<i>Previously, BarDweller (Ozzy Osborne) wrote…</i></summary>



> typo. implementations
> </details>
> Done.

---

_[mediator-app/src/main/java/org/gameontext/mediator/Constants.java, line 81 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURShpwrxTodB5V0Noy:-KURVAP9rKmjOKsA8Elh:b-896fix) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-app/src/main/java/org/gameontext/mediator/Constants.java#L81)):_
<details><summary>

<i>Previously, BarDweller (Ozzy Osborne) wrote…</i></summary>



> typo.. implementations
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by BarDweller** [comment]
Review status: 9 of 11 files reviewed at latest revision, 1 unresolved discussion.

---

_[mediator-wlpcfg/startup.sh, line 50 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67#-KURToY3uy1WXQUbiObS:-KURVKpzRfgVplFL57g1:b-m6z23d) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a02b1086b4c9c7e6197bdbd39bf6fdb1260d0d2f/mediator-wlpcfg/startup.sh#L50)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



>   &lt;include location="${env.GAMEON_MODE}-local.xml" optional="true" />
>   &lt;include location="${env.GAMEON_MODE}-logCollector.xml" optional="true" />
>   &lt;include location="${env.GAMEON_MODE}-messageHub.xml" optional="true" />
> </details>
> Aha.. I'd seen that but missed the connection, cute. 

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Comment by BarDweller** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/67)_

**Pull request merged**
