### PR TITLE
Jwt on open

### PR DESCRIPTION
**Pull request by ebullient**
Move processing of JWT earlier when connecting to mediator

---

This change is [Review on Reviewable](https://reviewable.io/reviews/gameontext/gameon-mediator/26)

### CODE REVIEW

**Comment by BarDweller** [comment]
Review status: 0 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 95 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRwz4AnH4Bt-yEkLk2:-KCRwz4AnH4Bt-yEkLk3:326486960) ([raw file](https://github.com/gameontext/gameon-mediator/blob/7feb26d0fdc799d2610d606256e2579a4b3d1a1c/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L95)):_
Any ideas on the lifecycle differences between static and @ApplicationScoped via @PostConstruct here? I think in our case they'll be equivalent. 

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 224 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRxRJNMdO0Oh6tBOGw:-KCRxRJO6DT9NElTvA1c:1285495549) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L224)):_
Should we test here if the jwt is non null .. in case this method gets invoked somehow before the validate one that pops it in the session.. and we could call it 'serverJwt' or something to give a hint as to why it isn't the client jwt that came in on the request.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerServerEndpoint.java, line 106 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRyW4YPfnT0CSsyQig:-KCRyW4YPfnT0CSsyQih:-1265187413) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerServerEndpoint.java#L106)):_
so umm.. what happens if it does take that long..  or longer (say if running on a raspberry pi)

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java, line 71 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRypf8zZy4jCzYAlii:-KCRypf8zZy4jCzYAlij:-204473718) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java#L71)):_
nice =)

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java, line 81 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRz-wok8cJrX-cSa7V:-KCRz-wok8cJrX-cSa7W:-2093950500) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java#L81)):_
I can't help but think a for loop with a break statement could have made this if check redundant.. 
Iter over the list, if you find something, process it then break out, else loop.. init code to missing jwt pre-loop, and if you fall out the end of the loop, then all's ready to go.. (may need to clear code for success.. but it's a little undefined what get failurecode should return if state is passed)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by ebullient** [comment]
Review status: 0 of 8 files reviewed at latest revision, 4 unresolved discussions.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 95 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRwz4AnH4Bt-yEkLk2:-KCS-2nb1XHyzUlTZ3yw:758240614) ([raw file](https://github.com/gameontext/gameon-mediator/blob/7feb26d0fdc799d2610d606256e2579a4b3d1a1c/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L95)):_
static is difficult to test. I consider it an anti-pattern when you can use injection instead. 

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 224 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRxRJNMdO0Oh6tBOGw:-KCS03cJlknmYFWR_9Rg:632178827) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L224)):_
can do, but at this point, there is a latch in the per-client-endpoint-instance that prevents the mediator-creation attempt until the JWT has been verified.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerServerEndpoint.java, line 106 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRyW4YPfnT0CSsyQig:-KCS0WSWtEOpRexCheiW:1966803052) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerServerEndpoint.java#L106)):_
Good question. One would argue that if it takes that long, the responsiveness will be so bad it won't be worth doing. This does point out that I should do the null check, probably immediately after this timeout.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java, line 81 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRz-wok8cJrX-cSa7V:-KCS0sbXzuW2whPIipn_:944579646) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/auth/JWT.java#L81)):_
y. which is why I left it the way it was... 

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by BarDweller** [comment]
Review status: 0 of 8 files reviewed at latest revision, 2 unresolved discussions.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 95 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRwz4AnH4Bt-yEkLk2:-KCS2d1B8As-mPrubJbw:-2015061072) ([raw file](https://github.com/gameontext/gameon-mediator/blob/7feb26d0fdc799d2610d606256e2579a4b3d1a1c/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L95)):_
Statics are simple to test via JMockit .. no harder than any other field type. Although without JMockit, it certainly used to be harder. 

And this field isn't using injection? this is just replacing a field that used to be init'd on first usage and kept in a static, with a field that's init'd when the parent object is constructed (ok, for injection to something else, but that's the PCM object, not the Key I'm referring to).. so I was querying the lifecycle difference between the key being static, and being tied to the ApplicationScoped lifecycle of the PCM. 

Now we could.. move the Key object here to be a custom type that extends Key.. like JWTKey .. and then declare a method with @Produces JWTKey (See CouchInjector over in Player repo).. and then we could declare JWTKey here with @Inject .. and it would all magically reconnect.. 

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 224 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRxRJNMdO0Oh6tBOGw:-KCS3qqu79oVsuw1RWVL:2097555767) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L224)):_
Yup.. saw that.. was figuring this method was public, so would just be to prevent madness while we had the chance.. after this, the jwt is cached into the mediators and it's too late to want to test it every time

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by BarDweller** [comment]
Reviewed 9 of 11 files at r1.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by ebullient** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 95 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRwz4AnH4Bt-yEkLk2:-KCS9-q7oE4a3yyDVJFr:-2026568295) ([raw file](https://github.com/gameontext/gameon-mediator/blob/7feb26d0fdc799d2610d606256e2579a4b3d1a1c/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L95)):_
It is filled out in @PostConstruct which is driven by CDI. There isn't any reason/advantage for it to be static.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by ebullient** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

_[mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java, line 224 [r1]](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26#-KCRxRJNMdO0Oh6tBOGw:-KCSCi7v6bqApxNZk6vh:453153862) ([raw file](https://github.com/gameontext/gameon-mediator/blob/a8993ce733d6f5ef84954cae4686398cff4099d9/mediator-app/src/main/java/net/wasdev/gameon/mediator/PlayerConnectionManager.java#L224)):_
yep. can check for null and close connection (as valid JWT not present)

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by BarDweller** [comment]
Reviewed 2 of 11 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by BarDweller** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by BarDweller** [comment]
Reviewed 2 of 3 files at r3.
Review status: 9 of 10 files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Comment by ebullient** [comment]
Reviewed 1 of 3 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/gameontext/gameon-mediator/26)_

**Pull request merged**
