### PR TITLE
Location update

### PR DESCRIPTION
**Pull request by BarDweller**
Start persisting location changes via player service, and respond to
player location change events (triggered by the location change
persisting). Remember this isn't entirely daft once you consider
multiple mediators running concurrently, only one will initiate the
change, the others must respond to it via the event. 

(This change builds on the kafkaagain branch)

Signed-off-by: Ozzy Osborne <ozzy@ca.ibm.com>

---
This change is [Reviewable](https://reviewable.io/reviews/gameontext/gameon-mediator/70)

### CODE REVIEW

**Comment by ebullient** [comment]
Did I miss tests for Kafka event stuff?

---

Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_[mediator-app/src/main/java/org/gameontext/mediator/MediatorNexus.java, line 409 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh-dJnGX9dQp0NEV9g:-KWh-dJnGX9dQp0NEV9h:b95nu74) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/MediatorNexus.java#L409)):_

> ``` Java
>         /**
>          * Perform the actual transition between rooms: not synchronized, as all callers are.
>          * @param newRoom
> ```

next change: 
- @param withUpdate

---

_[mediator-app/src/main/java/org/gameontext/mediator/PlayerClient.java, line 142 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh03VkJ-JUq6QtMDKo:-KWh03VkJ-JUq6QtMDKp:b-wccty) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/PlayerClient.java#L142)):_

> ``` Java
>             // string containing JSON
>             String resultString = target.request(MediaType.APPLICATION_JSON).accept(MediaType.APPLICATION_JSON)
>                     .header("Content-type", "application/json").put(Entity.json(parameter), String.class);
> ```

Why?! it is strange that we should do this this way... 

---

_[mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java, line 37 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh0UccRw6jB3M_e6-z:-KWh0UccRw6jB3M_e60-:b-iyvhz2) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java#L37)):_

> ``` Java
>       public void playerUpdated(String userId, String userName, String favoriteColor);    
>       public void locationUpdated(String userId, String newLocation);
>       //add additional methods as required for other event types...
> ```

whitespace

---

_[mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java, line 87 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh0_IjZdgkWuoVXFxN:-KWh0_IjZdgkWuoVXFxO:b2nhji7) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java#L87)):_

> ``` Java
>                   String location = player.get("location").asText();
> 
>                   System.out.println("LOCATION INVOKE "+location);
> ```

Log

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-:-KWh0nGOB6VFOe_MYnhI:bygwtk)_

**Comment by BarDweller** [comment]
Review status: 4 of 9 files reviewed at latest revision, 4 unresolved discussions.

---

_[mediator-app/src/main/java/org/gameontext/mediator/MediatorNexus.java, line 409 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh-dJnGX9dQp0NEV9g:-KWnBu_ertmqwN9LffD1:b-896fix) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/MediatorNexus.java#L409)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> next change: 
> - @param withUpdate
>   </details>
>   Done.

---

_[mediator-app/src/main/java/org/gameontext/mediator/PlayerClient.java, line 142 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh03VkJ-JUq6QtMDKo:-KWnAzl8PSdU_9ky-k2D:b4uiqd6) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/PlayerClient.java#L142)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> Why?! it is strange that we should do this this way... 
> </details>
> The previous code was assuming the result would be mappable into a JsonObject .. 

```
        JsonObject result = target.request(MediaType.APPLICATION_JSON).accept(MediaType.APPLICATION_JSON)
                .header("Content-type", "application/json").put(Entity.json(parameter), JsonObject.class);
```

But I ran into issues with that failing, and needed to know why, so altered it to get the result as a string, log it, then parse it.. using JsonReader which is the other json api that doesn't need a working ObjectMapper etc .. I think in the end the issue was with player response not being json at all, rather than ObjectMapper hating me. But since it worked.. I left as-is here. 

---

_[mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java, line 37 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh0UccRw6jB3M_e6-z:-KWnBpiU78Bs8XueSpLs:b-896fix) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java#L37)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> whitespace
> </details>
> Done.

---

_[mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java, line 87 at r1](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-KWh0_IjZdgkWuoVXFxN:-KWnBr4-I4nK4WD3R9wX:b-896fix) ([raw file](https://github.com/gameontext/gameon-mediator/blob/4b54dae69b9682f44201d1a27755eb709ff77e48/mediator-app/src/main/java/org/gameontext/mediator/events/MediatorEvents.java#L87)):_
<details><summary>

<i>Previously, ebullient (Erin Schnabel) wrote…</i></summary>



> Log
> </details>
> Done.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70)_

**Comment by BarDweller** [comment]
You didn't I did.. I've added some now =)

---

Review status: 3 of 9 files reviewed at latest revision, 3 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70#-:-KWoKtImKXdJSuOYlwYS:bx4dmx1)_

**Comment by ebullient** [comment]
Reviewed 6 of 6 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/gameontext/gameon-mediator/70)_

**Pull request merged**
